#!/bin/bash
### using functions for avoid dummy code
####user verification
USERID=$(id -u)

#####to know previous command/file execution lo em jarigindhi ani telusukovadaniki manam logs ni maintain chestunamu 
##log file lo evaru eppudu e file ni run chesraro telusukovadaniki manam log file ni create chestunamu

TIMESTAMP=$(date +%F-%H-%M-%S)

###logfile creation
SCRIPTNAME=$(echo $0 | cut -d "." -f1)
LOGFILE=$SCRIPTNAME-$TIMESTAMP.log

#####mentioning colors for user look
R="\e[31m]"
G="\e[32m]"
Y="\e[33m]"
N="\e[0m]"


if [ $USERID -ne 0 ]
then
    echo "PLease login with root user"
    Exit 2
else
    echo "your super user"
fi

VALIDATE()
{
    if [ $1 -ne 0 ]
    then
    echo -e "$2 ......$R failure $N"
    exit 3
    else
    echo -e "$2 ...$G success $N"
    fi
}

dnf install mysqlll-server -y &>> $LOGFILE   #redirectiond command results into lofile

VALIDATE $? "installing mysql server"

systemctl enable mysqld &>> $LOGFILE

VALIDATE $? "enabling mysqlid"
#####when we running this script every time the log file will be creating we can see this script u run and at whattime
