#!/bin/bash
### using functions for avoid dummy code
####user verification
USERID=$(id -u)

#####to know previous command/file execution lo em jarigindhi ani telusukovadaniki manam logs ni maintain chestunamu 
##log file lo evaru eppudu e file ni run chesraro telusukovadaniki manam log file ni create chestunamu

TIMESTAMP=$(date +%F-%H-%M-%S)

###logfile creation
SCRIPTNAME=$(echo $0 | cut -d "." -f1)
LOGFILE=$SCRIPTNAME-$TIMESTAMP.log

if [ $USERID -ne 0 ]
then
    echo "PLease login with root user"
    Exit 2
else
    echo "your super user"
fi

VALIDATE()
{
    if [ $1 -ne 0 ]
    then
    echo "$2 ......failure"
    Exit 3
    else
    echo "$2 ...success"
}

dnf install mysql-server -y &>> $LOGFILE   #redirectiond command results into lofile

VALIDATE $? "installing mysql server"

systemctl enable mysqld &>> $LOGFILE

VALIDATE $? "enabling mysqlid"
#####when we running this script every time the log file will be creating we can see this script u run and at whattime
